// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/adddomain.tsx";
import * as $1 from "./routes/admin.tsx";
import * as $2 from "./routes/api/adddomain.ts";
import * as $3 from "./routes/api/deletedomain.ts";
import * as $4 from "./routes/api/deleteuser.ts";
import * as $5 from "./routes/api/domain.ts";
import * as $6 from "./routes/api/login.ts";
import * as $7 from "./routes/api/records.ts";
import * as $8 from "./routes/api/register.ts";
import * as $9 from "./routes/api/status.ts";
import * as $10 from "./routes/api/ttl.ts";
import * as $11 from "./routes/dash.tsx";
import * as $12 from "./routes/domain.tsx";
import * as $13 from "./routes/domains.tsx";
import * as $14 from "./routes/index.tsx";
import * as $15 from "./routes/login.tsx";
import * as $16 from "./routes/register.tsx";
import * as $$0 from "./islands/AddDomain.tsx";
import * as $$1 from "./islands/Admin.tsx";
import * as $$2 from "./islands/Dashboard.tsx";
import * as $$3 from "./islands/DomainPage.tsx";
import * as $$4 from "./islands/Login.tsx";
import * as $$5 from "./islands/Register.tsx";

const manifest = {
  routes: {
    "./routes/adddomain.tsx": $0,
    "./routes/admin.tsx": $1,
    "./routes/api/adddomain.ts": $2,
    "./routes/api/deletedomain.ts": $3,
    "./routes/api/deleteuser.ts": $4,
    "./routes/api/domain.ts": $5,
    "./routes/api/login.ts": $6,
    "./routes/api/records.ts": $7,
    "./routes/api/register.ts": $8,
    "./routes/api/status.ts": $9,
    "./routes/api/ttl.ts": $10,
    "./routes/dash.tsx": $11,
    "./routes/domain.tsx": $12,
    "./routes/domains.tsx": $13,
    "./routes/index.tsx": $14,
    "./routes/login.tsx": $15,
    "./routes/register.tsx": $16,
  },
  islands: {
    "./islands/AddDomain.tsx": $$0,
    "./islands/Admin.tsx": $$1,
    "./islands/Dashboard.tsx": $$2,
    "./islands/DomainPage.tsx": $$3,
    "./islands/Login.tsx": $$4,
    "./islands/Register.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
